#!/bin/bash
./build src/index.ts x86_64-apple-darwin ${1}
./build src/index.ts x86_64-pc-windows-msvc ${1}
./build src/index.ts aarch64-apple-darwin ${1}
./build src/index.ts x86_64-unknown-linux-gnu ${1}

tar -czf owl-release-${1}.tar.gz owl